### ISSUE TITLE
which sat solver?

### ISSUE THREAD

**Issue by one30** [Ko-/sboxoptimization#3]
Hi Ko-,
I'm tring use this repo for the rectangle wiht gc = 11,
and I use the minisat as my sat solver,
but it seem like that the format is not correct by using the minisat.
Could you tell me which sat solver you use?

Thank you very much!

**Comment by Ko-** [comment]
Hi. I used both MiniSat and CryptoMiniSat but if I recall correctly then they use the same input format. I found the following files, could you check if they're similar to what you have and if they work?

[rectangle_gc11.eqs.txt](https://github.com/Ko-/sboxoptimization/files/6604845/rectangle_gc11.eqs.txt)
[rectangle_gc11.cnf.txt](https://github.com/Ko-/sboxoptimization/files/6604846/rectangle_gc11.cnf.txt)

**Comment by one30** [comment]
Hi，Ko-！Thank you for your reply!

Your rectangle_gc11.eqs.txt is same to me, but the rectangle_gc11.cnf.txt isn't.
I have tried xl0.exe with  rectangle_gc11.eqs in win10'CMD to generate my rectangle_gc11.cnf,
[rectangle_gc11.eqs.cnf.txt](https://github.com/Ko-/sboxoptimization/files/6607255/rectangle_gc11.eqs.cnf.txt)
and i noticed that my rectangle_gc11.cnf isn't similar to yours.

Could you give me some advice?

**Comment by Ko-** [comment]
Well it may not be the same (probably because we used different versions of that xl0.exe tool), but it is very similar. A line that starts with a `c` is a comment that should be ignored by the SAT solver. The `p cnf 10575 36586` says that the instance is in CNF format, uses 10575 variables and has 36586 clauses. What follows are 36586 lines that all end with a 0. I'm able to run CryptoMiniSat on the file that you uploaded without errors.

**Comment by one30** [comment]
Oh, I get it!
I run CryptoMiniSat with rectangle_gc11.eqs.cnf in about 8 hours to generate rectangle_gc11.eqs.cnf.claim without errors,
[rectangle_gc11.eqs.cnf.claimwithCryptoMinSat.txt](https://github.com/Ko-/sboxoptimization/files/6616604/rectangle_gc11.eqs.cnf.claimwithCryptoMinSat.txt)


but I run cnfclaimtoclaim.py and i got an empty rectangle_gc11.eqs.claim.txt, an error occured with  

'Traceback (most recent call last):
  File "./cnfclaimtoclaim.py", line 35, in <module>
    elif int(x) in d:
ValueError: invalid literal for int() with base 10: 'c''

Is that my rectangle_gc11.eqs.cnf.claim's format not correct?

By the way, I also use minisat to generate rectangle_gc11.eqs.cnf.claim and then an similar error occured when I  run cnfclaimtoclaim.py .
[rectangle_gc11.eqs.cnf.claimwithminisat.txt](https://github.com/Ko-/sboxoptimization/files/6616630/rectangle_gc11.eqs.cnf.claimwithminisat.txt)

Thanks!

**Comment by Ko-** [comment]
Ah, so that's where the error occurs. In your first example (CryptoMiniSat) the file is indeed in a somewhat different format than I used, but it should be easy to change. The Python script expects a single line with the answer (SATISFIABLE or not) and, if it is satisfiable, then a second line that contains the valuation of all variables. In your case there are more than 15000 lines of comments (prefixed with a `c`) that you should ignore, then the answer and finally the valuation of all variables that is spread over multiple lines, prefixed with a `v`.

Your second example (MiniSat) only has the answer and some statistics, but doesn't contain the valuation of all variables. According to [this site](https://dwheeler.com/essays/minisat-user-guide.html) if you invoke MiniSat with an output file, then it should give a satisfying valuation that can be parsed by cnfclaimtoclaim.py.

**Comment by one30** [comment]
Wow, that's why my cnf.claim can't run with cnfclaimtoclaim.py.
I can run this repo in the correct way finally!
Thank you for your patience!
Wish you a good day! 😄
